# =============================================================================
# PREPROCESSED RASTERS CONFIG (EPSG:5070, Template-Aligned)
# =============================================================================
# Auto-generated by PHASE4_00_preprocess_rasters.R
#
# All rasters aligned to template grids in EPSG:5070 and clipped to AOI
# =============================================================================
# PREPROCESSED VARIANT — use when rasters are already resampled/aligned to target grid
# If rasters need resampling first, use PHASE4_config_covariates.R instead

preprocessed_count <- 0
missing_count <- 0

for (cov_name in names(COVARIATES)) {
  cov <- COVARIATES[[cov_name]]
  
  new_path <- file.path(
    if (cov$scale == "fine") PHASE4_CONFIG$paths$cov_fine else PHASE4_CONFIG$paths$cov_coarse,
    basename(cov$path)
  )
  
  if (file.exists(new_path)) {
    COVARIATES[[cov_name]]$path <- new_path
    COVARIATES[[cov_name]]$preprocessed <- TRUE
    preprocessed_count <- preprocessed_count + 1
  } else {
    COVARIATES[[cov_name]]$preprocessed <- FALSE
    missing_count <- missing_count + 1
  }
}

if (preprocessed_count > 0) {
  cat("✓ Using", preprocessed_count, "preprocessed rasters (EPSG:5070, template-aligned)\n")
}

if (missing_count > 0) {
  cat("ℹ", missing_count, "rasters using originals\n")
}

